### ISSUE TITLE
Crash on Smartphone

### ISSUE THREAD

**Issue by TonyRideBike** [TonyRideBike/Sunshine_TonyLYU#4]

**Comment by TonyRideBike** [comment]
```
                                                                        --------- beginning of crash
04-18 17:36:04.918 3660-3660/com.dev.tonylyu.sunshine E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.dev.tonylyu.sunshine, PID: 3660
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dev.tonylyu.sunshine/com.dev.tonylyu.sunshine.DetailActivity}: java.lang.IllegalArgumentException: No view found for id 0x7f0f0075 (com.dev.tonylyu.sunshine:id/weather_detail_container) for fragment DetailFragment{cf6ab15 #0 id=0x7f0f0075}
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                            at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                         Caused by: java.lang.IllegalArgumentException: No view found for id 0x7f0f0075 (com.dev.tonylyu.sunshine:id/weather_detail_container) for fragment DetailFragment{cf6ab15 #0 id=0x7f0f0075}
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1293)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                            at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                            at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                            at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                            at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                            at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                                            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                                                                            at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                                                                            at com.dev.tonylyu.sunshine.DetailActivity.onStart(DetailActivity.java:68)
                                                                            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
                                                                            at android.app.Activity.performStart(Activity.java:6679)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2609)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                                            at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:154) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
```

**Comment by TonyRideBike** [comment]
```java
// ...
    setContentView(R.layout.activity_detail);
// ...
    getSupportFragmentManager().beginTransaction().add(R.id.container, detailFragment).commit();
// ...
```

added id should be same as this Activity's layout id.
